#!/bin/sh

REALUSER=`users | cut -d ' ' -f 1`

glib-compile-schemas /usr/share/glib-2.0/
mkdir /home/$REALUSER/.worklist
mv /usr/share/worklist/data /home/$REALUSER/.worklist
chown -R $REALUSER:$REALUSER /home/$REALUSER/.worklist

