#!/bin/sh

REALUSER=`users | cut -d ' ' -f 1`

glib-compile-schemas /usr/share/glib-2.0/


if [ -d "/home/$REALUSER/.worklist" ]; then
	rm -r /home/$REALUSER/.worklist
fi

mkdir /home/$REALUSER/.worklist
mv /usr/share/worklist/data /home/$REALUSER/.worklist
chown -R $REALUSER:$REALUSER /home/$REALUSER/.worklist

if [ ! -e "/home/$REALUSER/.config/autostart/WorkList.desktop" ]; then
	ln -s /usr/share/applications/WorkList.desktop \
		/home/$REALUSER/.config/autostart/WorkList.desktop
fi
